Traceback (most recent call last):
  File "/home/pedro/PINN/jaxpi/examples/geomII/main.py", line 39, in <module>
    app.run(main)
  File "/usr/local/lib/python3.11/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.11/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/pedro/PINN/jaxpi/examples/geomII/main.py", line 31, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/home/pedro/PINN/jaxpi/examples/geomII/train.py", line 46, in train_and_evaluate
    ) = get_dataset()
        ^^^^^^^^^^^^^
  File "/home/pedro/PINN/jaxpi/examples/geomII/utils.py", line 80, in get_dataset
    u_fem, v_fem, p_fem, coords_fem = get_fem_data()
                                      ^^^^^^^^^^^^^^
  File "/home/pedro/PINN/jaxpi/examples/geomII/utils.py", line 25, in get_fem_data
    return jax.device_put(u_fem), jax.device_put(v_fem), jax.device_put(p_fem), jax.device_put(coord)
           ^^^
NameError: name 'jax' is not defined