
Waiting for JIT...
[13:31:53 - main - INFO] -----------------------------
[13:31:53 - main - INFO] Iter:   0      Time: 11.324
[13:31:53 - main - INFO] -------------  --------------
[13:31:53 - main - INFO] p_in_loss      6.705e-01
[13:31:53 - main - INFO] p_out_loss     3.013e-01
[13:31:53 - main - INFO] rc_loss        4.806e+01
[13:31:53 - main - INFO] ru_loss        2.483e+02
[13:31:53 - main - INFO] rv_loss        8.813e+02
[13:31:53 - main - INFO] u_noslip_loss  1.143e-01
[13:31:53 - main - INFO] v_noslip_loss  1.682e-01
[13:31:53 - main - INFO] u_error        1.267e+00
[13:31:53 - main - INFO] v_error        5.618e+00
[13:31:55 - main - INFO] ----------------------------
[13:31:55 - main - INFO] Iter: 100      Time: 0.007
[13:31:55 - main - INFO] -------------  -------------
[13:31:55 - main - INFO] p_in_loss      5.852e-04
[13:31:55 - main - INFO] p_out_loss     3.517e-04
[13:31:55 - main - INFO] rc_loss        1.836e-01
[13:31:55 - main - INFO] ru_loss        4.899e-01
[13:31:55 - main - INFO] rv_loss        4.042e-01
[13:31:55 - main - INFO] u_noslip_loss  2.246e-04
[13:31:55 - main - INFO] v_noslip_loss  1.899e-04
[13:31:55 - main - INFO] u_error        9.154e-01
[13:31:55 - main - INFO] v_error        9.958e-01
I0515 13:31:55.249165 124645538619392 checkpoints.py:574] Saving checkpoint at step: 110
I0515 13:31:55.249527 124645538619392 checkpoints.py:662] Using Orbax as backend to save Flax checkpoints. For potential troubleshooting see: https://flax.readthedocs.io/en/latest/guides/training_techniques/use_checkpointing.html#orbax-as-backend-troubleshooting
W0515 13:31:55.249787 124645538619392 type_handlers.py:302] SaveArgs.aggregate is deprecated, please use custom TypeHandler (https://orbax.readthedocs.io/en/latest/custom_handlers.html#typehandler) or contact Orbax team to migrate before May 1st, 2024. If your Pytree has empty ([], {}, None) values then use PyTreeCheckpointHandler(..., write_tree_metadata=True, ...) or use StandardCheckpointHandler to avoid TypeHandler Registry error. Please note that PyTreeCheckpointHandler.write_tree_metadata default value is already set to True.
I0515 13:31:55.250202 124645538619392 checkpointer.py:137] Saving item to ckpt/checkpoint_110.
-----------
default
./ckpt
Traceback (most recent call last):
  File "/usr/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/root/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/pedro/PINN/jaxpi/examples/geomII/main.py", line 39, in <module>
    app.run(main)
  File "/usr/local/lib/python3.11/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.11/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/pedro/PINN/jaxpi/examples/geomII/main.py", line 31, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/home/pedro/PINN/jaxpi/examples/geomII/train.py", line 138, in train_and_evaluate
    save_checkpoint(model.state, path)#, keep=config.saving.num_keep_ckpts)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jaxpi/utils.py", line 44, in save_checkpoint
    checkpoints.save_checkpoint(workdir, state, step=step, keep=keep)
  File "/usr/local/lib/python3.11/dist-packages/flax/training/checkpoints.py", line 697, in save_checkpoint
    orbax_checkpointer.save(
  File "/usr/local/lib/python3.11/dist-packages/orbax/checkpoint/checkpointer.py", line 156, in save
    self._handler.finalize(tmpdir)
  File "/usr/local/lib/python3.11/dist-packages/orbax/checkpoint/pytree_checkpoint_handler.py", line 1493, in finalize
    type_handlers.merge_ocdbt_per_process_files(directory)
  File "/usr/local/lib/python3.11/dist-packages/orbax/checkpoint/type_handlers.py", line 646, in merge_ocdbt_per_process_files
    parent_tspec = get_tensorstore_spec(os.fspath(directory), use_ocdbt=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/orbax/checkpoint/type_handlers.py", line 756, in get_tensorstore_spec
    raise ValueError(f'Checkpoint path should be absolute. Got {directory}')
ValueError: Checkpoint path should be absolute. Got ckpt/checkpoint_110.orbax-checkpoint-tmp-1715779915250463
Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1583, in _shutdown
    lock.acquire()
