2024-05-15 13:31:19,197 INFO    MainThread:253682 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-05-15 13:31:19,197 INFO    MainThread:253682 [wandb_setup.py:_flush():76] Configure stats pid to 253682
2024-05-15 13:31:19,197 INFO    MainThread:253682 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-05-15 13:31:19,197 INFO    MainThread:253682 [wandb_setup.py:_flush():76] Loading settings from /home/pedro/PINN/jaxpi/examples/geomII/wandb/settings
2024-05-15 13:31:19,197 INFO    MainThread:253682 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-15 13:31:19,197 INFO    MainThread:253682 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-15 13:31:19,197 INFO    MainThread:253682 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/home/pedro/PINN/jaxpi/examples/geomII/main.py', 'program': '/home/pedro/PINN/jaxpi/examples/geomII/main.py'}
2024-05-15 13:31:19,197 INFO    MainThread:253682 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-15 13:31:19,197 INFO    MainThread:253682 [wandb_init.py:_log_setup():521] Logging user logs to /home/pedro/PINN/jaxpi/examples/geomII/wandb/run-20240515_133119-o1346mfs/logs/debug.log
2024-05-15 13:31:19,198 INFO    MainThread:253682 [wandb_init.py:_log_setup():522] Logging internal logs to /home/pedro/PINN/jaxpi/examples/geomII/wandb/run-20240515_133119-o1346mfs/logs/debug-internal.log
2024-05-15 13:31:19,198 INFO    MainThread:253682 [wandb_init.py:init():561] calling init triggers
2024-05-15 13:31:19,198 INFO    MainThread:253682 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-05-15 13:31:19,198 INFO    MainThread:253682 [wandb_init.py:init():611] starting backend
2024-05-15 13:31:19,198 INFO    MainThread:253682 [wandb_init.py:init():615] setting up manager
2024-05-15 13:31:19,199 INFO    MainThread:253682 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-15 13:31:19,199 INFO    MainThread:253682 [wandb_init.py:init():623] backend started and connected
2024-05-15 13:31:19,200 INFO    MainThread:253682 [wandb_init.py:init():715] updated telemetry
2024-05-15 13:31:19,200 INFO    MainThread:253682 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-05-15 13:31:19,221 WARNING MainThread:253682 [wandb_init.py:init():1203] interrupted
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
          ^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_init.py", line 751, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/threading.py", line 622, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-05-15 13:31:21,934 WARNING MsgRouterThr:253682 [router.py:message_loop():77] message_loop has been closed
